Repository simoboye/BDSA2020, pull requests merged in 2020-12, with the labels that each got.

#12 Placement swipe view
  .vscode/launch.json
  BDSA2020.View/Pages/Index.razor
  BDSA2020.View/Pages/PlacementDescriptionView.razor
  BDSA2020.View/Pages/StudentRepository.Razor
  BDSA2020.View/Pages/_Host.cshtml
  BDSA2020.View/wwwroot/css/placementStyle.css
  BDSA2020.View/wwwroot/main.js
Labels: enhancement

#15 Implementation of checking algorithm for companies
  BDSA2020.Api.Tests/CompanyRepositoryControllerTests.cs
  BDSA2020.Api/Controllers/CompanyRepositoryController.cs
  BDSA2020.Api/Startup.cs
  BDSA2020.Entities/Context.cs
  BDSA2020.Entities/Data/Company.cs
  BDSA2020.Entities/Data/CompanyPlacement.cs
  BDSA2020.Entities/Data/PlacementDescription.cs
  BDSA2020.Entities/IContext.cs
  BDSA2020.Models.Tests/CompanyRepositoryTests.cs
  BDSA2020.Models.Tests/PlacementDescriptionRepositoryTests.cs
  BDSA2020.Models.Tests/StudentRepositoryTests.cs
  BDSA2020.Models/CompanyRepository.cs
  BDSA2020.Models/ICompanyRepository.cs
  BDSA2020.Shared/CompanyDetailsDTO.cs
  BDSA2020.Shared/CreateCompanyDTO.cs
  BDSA2020.Shared/UpdateCompanyDTO.cs
  BDSA2020.View/Pages/Index.razor
  BDSA2020.View/Pages/UserStatusCheck.razor
Labels: enhancement

#20 Created endpoints for save and unsave
  .gitignore
  BDSA2020.Api.Tests/StudentRepositoryControllerTests.cs
  BDSA2020.Api/Controllers/PlacementDescriptionRepositoryControllor.cs
  BDSA2020.Api/Controllers/StudentRepositoryControllor.cs
  BDSA2020.Entities/Context.cs
  BDSA2020.Models.Tests/StudentRepositoryTests.cs
  BDSA2020.Models/IStudentRepository.cs
  BDSA2020.Models/StudentRepository.cs
  BDSA2020.View/Pages/Index.razor
Labels: enhancement

#26 Added new colors
  BDSA2020.View/wwwroot/css/placementStyle.css
  BDSA2020.View/wwwroot/css/settingsStyle.css
  BDSA2020.View/wwwroot/css/site.css
Labels: easy fix, enhancement

#27 succesfull fetching
  BDSA2020.View/Pages/PlacementDescriptionView.razor
  BDSA2020.View/wwwroot/main.js
Labels: easy fix, enhancement

#29 Cleaned-up tests
  BDSA2020.Api.Tests/CompanyRepositoryControllerTests.cs
  BDSA2020.Api.Tests/PlacementDescriptionRepositoryControllerTests.cs
  BDSA2020.Api.Tests/StudentRepositoryControllerTests.cs
  BDSA2020.Models.Tests/CompanyRepositoryTests.cs
  BDSA2020.Models.Tests/PlacementDescriptionRepositoryTests.cs
  BDSA2020.Models.Tests/StudentRepositoryTests.cs
Labels: enhancement, test-improvement

#35 Logout error fix
  BDSA2020.View/Pages/RedirectLogout.razor
  BDSA2020.View/Shared/RedirectToLogin.razor
Labels: bug, enhancement

#34 Implemented first draft of matching algorithm
  BDSA2020.View.Tests/MatchingServiceTests.cs
  BDSA2020.View/Data/PlacementDescriptionMatch.cs
  BDSA2020.View/Data/Service/IMatchingService.cs
  BDSA2020.View/Data/Service/MatchingService.cs
  BDSA2020.View/Data/Service/UserPropertiesService.cs
  BDSA2020.View/Data/WeatherForecast.cs
  BDSA2020.View/Data/WeatherForecastService.cs
  BDSA2020.View/Pages/Index.razor
  BDSA2020.View/Pages/PlacementDescriptionView.razor
  BDSA2020.View/Startup.cs
Labels: enhancement

#38 Http client requests from view
  BDSA2020.Entities/Context.cs
  BDSA2020.Models.Tests/PlacementDescriptionRepositoryTests.cs
  BDSA2020.Models/StudentRepository.cs
  BDSA2020.View/Pages/MySavesView.razor
  BDSA2020.View/Pages/PlacementDescriptionCreationView.razor
  BDSA2020.View/Pages/PlacementDescriptionView.razor
Labels: enhancement

#47 Nav Buttons works now
  BDSA2020.View/Pages/PlacementDescriptionView.razor
  BDSA2020.View/wwwroot/css/placementStyle.css
  BDSA2020.View/wwwroot/main.js
Labels: bug, easy fix, enhancement

#46 Updated page on removed description
  BDSA2020.View/Pages/MySavesView.razor
Labels: easy fix

#50 Finalization of view
  BDSA2020.View/Pages/CompanySettingsView.razor
  BDSA2020.View/Pages/PlacementDescriptionCreationView.razor
  BDSA2020.View/Pages/PlacementDescriptionView.razor
  BDSA2020.View/Pages/ProfileSettingsView.razor
  BDSA2020.View/Shared/NavMenu.razor
  BDSA2020.View/wwwroot/css/placementStyle.css
  BDSA2020.View/wwwroot/main.js
Labels: bug, easy fix, enhancement

#53 Company settings implementation
  BDSA2020.View/Pages/CompanySettingsView.razor
  BDSA2020.View/Shared/RedirectLogout.razor
  BDSA2020.View/Startup.cs
  BDSA2020.View/wwwroot/favicon.ico
Labels: bug

#54 Topic/profile settings final steps
  BDSA2020.Entities/Context.cs
  BDSA2020.Models.Tests/PlacementDescriptionRepositoryTests.cs
  BDSA2020.View/Pages/CompanyPlacements.razor
  BDSA2020.View/Pages/MySavesView.razor
  BDSA2020.View/Pages/PlacementDescriptionView.razor
  BDSA2020.View/Pages/ProfileSettingsView.razor
Labels: bug, enhancement
